/*
 * qTest Manager API Version 8.6 - 10.5
 * qTest Manager API Version 8.6 - 10.5
 *
 * OpenAPI spec version: 8.6 - 10.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * IntegrationReleaseMappingResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-03-04T15:34:58.501Z")
public class IntegrationReleaseMappingResponse {
  @SerializedName("externalProjectId")
  private String externalProjectId = null;

  @SerializedName("externalIssueTypeId")
  private String externalIssueTypeId = null;

  @SerializedName("data_retrieval_options")
  private List<String> dataRetrievalOptions = new ArrayList<String>();

  @SerializedName("auto_update_release_scope")
  private String autoUpdateReleaseScope = null;

  public IntegrationReleaseMappingResponse externalProjectId(String externalProjectId) {
    this.externalProjectId = externalProjectId;
    return this;
  }

   /**
   * Get externalProjectId
   * @return externalProjectId
  **/
  @ApiModelProperty(example = "10031", value = "")
  public String getExternalProjectId() {
    return externalProjectId;
  }

  public void setExternalProjectId(String externalProjectId) {
    this.externalProjectId = externalProjectId;
  }

  public IntegrationReleaseMappingResponse externalIssueTypeId(String externalIssueTypeId) {
    this.externalIssueTypeId = externalIssueTypeId;
    return this;
  }

   /**
   * Get externalIssueTypeId
   * @return externalIssueTypeId
  **/
  @ApiModelProperty(example = "Sprint", value = "")
  public String getExternalIssueTypeId() {
    return externalIssueTypeId;
  }

  public void setExternalIssueTypeId(String externalIssueTypeId) {
    this.externalIssueTypeId = externalIssueTypeId;
  }

  public IntegrationReleaseMappingResponse dataRetrievalOptions(List<String> dataRetrievalOptions) {
    this.dataRetrievalOptions = dataRetrievalOptions;
    return this;
  }

  public IntegrationReleaseMappingResponse addDataRetrievalOptionsItem(String dataRetrievalOptionsItem) {
    this.dataRetrievalOptions.add(dataRetrievalOptionsItem);
    return this;
  }

   /**
   * Get dataRetrievalOptions
   * @return dataRetrievalOptions
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getDataRetrievalOptions() {
    return dataRetrievalOptions;
  }

  public void setDataRetrievalOptions(List<String> dataRetrievalOptions) {
    this.dataRetrievalOptions = dataRetrievalOptions;
  }

   /**
   * Get autoUpdateReleaseScope
   * @return autoUpdateReleaseScope
  **/
  @ApiModelProperty(example = "true", value = "")
  public String getAutoUpdateReleaseScope() {
    return autoUpdateReleaseScope;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IntegrationReleaseMappingResponse integrationReleaseMappingResponse = (IntegrationReleaseMappingResponse) o;
    return Objects.equals(this.externalProjectId, integrationReleaseMappingResponse.externalProjectId) &&
        Objects.equals(this.externalIssueTypeId, integrationReleaseMappingResponse.externalIssueTypeId) &&
        Objects.equals(this.dataRetrievalOptions, integrationReleaseMappingResponse.dataRetrievalOptions) &&
        Objects.equals(this.autoUpdateReleaseScope, integrationReleaseMappingResponse.autoUpdateReleaseScope);
  }

  @Override
  public int hashCode() {
    return Objects.hash(externalProjectId, externalIssueTypeId, dataRetrievalOptions, autoUpdateReleaseScope);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IntegrationReleaseMappingResponse {\n");
    
    sb.append("    externalProjectId: ").append(toIndentedString(externalProjectId)).append("\n");
    sb.append("    externalIssueTypeId: ").append(toIndentedString(externalIssueTypeId)).append("\n");
    sb.append("    dataRetrievalOptions: ").append(toIndentedString(dataRetrievalOptions)).append("\n");
    sb.append("    autoUpdateReleaseScope: ").append(toIndentedString(autoUpdateReleaseScope)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

